trigger:
  - main
pool:
    vmImage: ubuntu-latest
variables:
    buildConfiguration: 'Release'
steps:
- scrpit: dotnet build --configuration $(buildConfiguration)
  display:'dotnet build $(buildConfiguration)'